killer/urls.py
from greek.views import homegreek, greekfeedback, greekallmyfeedback, greekviewfeedback, \
    greekdeletedfeedback, greekviewdeletedfeedback, greekdeletefeedback, greeksignupuser, \
    greekloginuser, greekorder, greekallmyorders, greekvieworder, greekdeleteorder, greekdeletedorders, greekreviewdeletedorders, greekdeletedeletedorder, greeklogoutuser
from django.contrib import admin
from django.urls import path
from web import views
path('greek/signup/', greeksignupuser, name='greeksignupuser'),
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    
    # Greek
    path('greek/', homegreek, name="homegreek"),
    path('greek/login/', greekloginuser, name='greekloginuser'),
    path('greek/signup/', greeksignupuser, name='greeksignupuser'),
    path('greek/greeklogoutuser/', greeklogoutuser, name='greeklogoutuser'),
    path('greek/feedback/', greekfeedback, name="greekfeedback"),
    path('greek/allmyfeedback/', greekallmyfeedback, name="greekallmyfeedback"),
    path('greek/viewfeedback/<int:feedback_pk>', greekviewfeedback, name='greekviewfeedback'),
    path('greek/deleted', greekdeletedfeedback, name='greekdeletedfeedback'),
    path('greek/viewdeleted/<int:feedback_pk>', greekviewdeletedfeedback, name='greekviewdeletedfeedback'),
    path('greek/viewfeedback/<int:feedback_pk>/delete', greekdeletefeedback, name='greekdeletefeedback'),

    # Greek Order
    path('greek/order/', greekorder, name='greekorder'),
    path('greek/allmyorders/', greekallmyorders, name='greekallmyorders'),
    path('greek/vieworder/<int:order_pk>', greekvieworder, name='greekvieworder'),
    path('greek/deleteorder/<int:order_pk>', greekdeleteorder, name='greekdeleteorder'),
    path('greek/deletedorders/', greekdeletedorders, name='greekdeletedorders'),
    path('greek/reviewdeletedorders/<int:order_pk>', greekreviewdeletedorders, name='greekreviewdeletedorders'),
    path('greek/deletedeletedorder/<int:order_pk>', greekdeletedeletedorder, name='greekdeletedeletedorder'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('homelogout/', views.homelogoutuser, name='homelogoutuser'),
    
    # FeedBack
    path('feedback/', views.feedback, name='feedback'),
    path('welcomefeedback/', views.welcomefeedback, name='welcomefeedback'),
    path('allmyfeedback/', views.allmyfeedback, name='allmyfeedback'),
    path('viewfeedback/<int:feedback_pk>', views.viewfeedback, name='viewfeedback'),
    path('viewfeedback/<int:feedback_pk>/delete', views.deletefeedback, name='deletefeedback'),
    path('deleted', views.deletedfeedback, name='deletedfeedback'), # Δοκίμαζε μια με / μια χωρίς /. Με έχει πρήξει.
    path('viewdeleted/<int:feedback_pk>', views.viewdeletedfeedback, name='viewdeletedfeedback'),  
    
    #Order
    path('order/', views.order, name='order'),
    path('allmyorders/', views.allmyorders, name='allmyorders'),
    path('vieworder/<int:order_pk>', views.vieworder, name='vieworder'),
    path('deleteorder/<int:order_pk>', views.deleteorder, name='deleteorder'),
    
    path('deleteorder/<int:order_pk>', views.deletedeletedorder, name='deletedeletedorder'), 
    
    path('deletedorders/', views.deletedorders, name='deletedorders'),  
    path('reviewdeletedorders/<int:order_pk>', views.reviewdeletedorders, name='reviewdeletedorders'),

    # mobilelist
    path('mobilelist/', views.mobile, name='mobile'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from typing import Counter
# from web.views import feedback
from django.db import models
from .storage import OverwriteStorage
from django.contrib.auth.models import User


# Create your models here.


# def image_path(instance, filename):
#     return os.path.join('images', str(instance.some_identifier), filename)


class Image(models.Model):
    # Το pip install django-cleanup σβήνει την Photo όταν κάνεις delete απο το admin. Τώρα το έχω περασμένο μέσα. Το ΕΒΓΑΛΑ
    title = models.CharField(max_length=100, blank=True)
    image = models.ImageField(
        storage=OverwriteStorage(), upload_to='images', null=True)

    def __str__(self):
        return self.title


# class Citie(models.Model):
#   # Το pip install django-cleanup σβήνει την Photo όταν κάνεις delete απο το admin. Τώρα το έχω περασμένο μέσα. Το ΕΒΓΑΛΑ
#   city_name = models.CharField(max_length=100, blank=True)
#   city_photo = models.ImageField(storage=OverwriteStorage(), upload_to='cities', null=True)

#   def __str__(self):
#       return self.city_name


class CityDetail(models.Model):
    # Το pip install django-cleanup σβήνει την Photo όταν κάνεις delete απο το admin. Τώρα το έχω περασμένο μέσα. Το ΕΒΓΑΛΑ.
    city_name = models.CharField(max_length=100, blank=True)
    person_clients = models.CharField(max_length=100, blank=True)
    top_chefs = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    city_photo = models.ImageField(
        storage=OverwriteStorage(), upload_to='cities', null=True)

    def __str__(self):
        return self.city_name + "  " + "Restaurant Details"


class Feeddback(models.Model):
    customer_first_name = models.CharField(max_length=100, blank=True)
    customer_second_name = models.CharField(max_length=100, blank=True)
    feedback_description = models.CharField(max_length=100, blank=True)

    created = models.DateTimeField(auto_now_add=True, blank=True)

    datecompleted = models.DateTimeField(null=True, blank=True)
    # Κλειδώνει τον User με το σιγκεκριένο Feedback
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) 

    # Δεν χρειάζεται Migration η κάθε αλλαγή εντός των παραμέτρων. ΔΕΝ βάζω Blank=True γιατί θέλω να αφήνει Feedback Υποχρεωτικά.
    feedback = models.TextField(max_length=1000)
    customer_photo = models.ImageField(storage=OverwriteStorage(), upload_to='customer', null=True, blank=True)
    deleted = models.BooleanField()
    show = models.BooleanField(default=False)

    def __str__(self):
        return self.customer_second_name + " " + self.customer_first_name + ":" + "  " + "Feedback"


class Order(models.Model):
    FRANCE = 'France'
    GERMANY = 'Germany'
    UK = 'Great Britain'
    GREECE = 'Greece'
    COUNTRIES = [(FRANCE, 'France'), (GERMANY, 'Germany'), (UK, 'Great Britain'), (GREECE, 'Greece')]

    country = models.CharField(max_length=20, choices=COUNTRIES, default=GREECE)

    town = models.CharField(max_length=100, blank=True)
    
    address = models.CharField(max_length=100, blank=True)
    postalcode = models.CharField(max_length=10, blank=True)

    customer_first_name = models.CharField(max_length=100, blank=True)
    customer_second_name = models.CharField(max_length=100, blank=True)
    order_description = models.CharField(max_length=100, blank=True)

    placed = models.DateTimeField(auto_now_add=True, blank=True)

    datecompleted = models.DateTimeField(null=True, blank=True)
    # Κλειδώνει τον User με το σιγκεκριένο Feedback
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    # Δεν χρειάζεται Migration η κάθε αλλαγή εντός των παραμέτρων. ΔΕΝ βάζω Blank=True γιατί θέλω να αφήνει Feedback Υποχρεωτικά.
    order = models.TextField(max_length=1000)
    customer_photo = models.ImageField(
        storage=OverwriteStorage(), upload_to='customer', null=True, blank=True)
    deleted = models.BooleanField()
    # show = models.BooleanField(default=False)

    def __str__(self):
        return self.customer_second_name + " " + self.customer_first_name + ":" + "  " + "Order"


class ListOrNot(models.Model):
    lista = models.BooleanField(default=True)

web/templates/web/allmyorders.html
{% extends 'web/base.html' %}
{% block content %}

{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

  <!-- Bootstrap CSS -->

  <!-- Bootstrap CSS -->

  <link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'grid.css' %}"> 

  <link rel="stylesheet" type="text/css" href="{% static 'allmyfeedback4.css' %}">
  
  <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap"  
      rel="stylesheet">

    <title>DioniWines</title>

</head>

<body>
<div class="col span-1-of-2 box">
  <!-- <div class="row justify-content-center mt-5">
    <div class="col-md-10"> -->
      <div class="container-md">

        <div class="row">
          <div class="form">

              
            
            <form method="GET" action="#">
              
              <div class="form-style">
                
                {% if saved %}
                
                <div class="alert-saved">
                  <h1>
                    {{ saved }}
                  </h1>
                </div>
                {% endif %}
                
                <br> <br>
                
                {% if orders %}
                <div class="alert">
                  <h1>{{ orders.count }} Current Order{{ orders.count|pluralize }}</h1>
                  {% else %}
                  
                  <h1>You Have Not Placed Any Orders Yet</h1>
                </div>
                
                {% endif %}
                
              </div>
              
              <br>
              
              {% for order in orders %}
              <a href="{% url 'vieworder' order.id %}">
                <ul>
                  
                  <li>
                    
                    <div class="btn">
                      
                      {{ order.order_description }}
                      
                    </div>
                    
                  </li>
                </ul>
              </a>
              {% endfor %}
              
              
            </div>
            
            
            
          </form>
        </div>
        
        <!-- </div>
        </div>-->
        
      </div>
      
  </div>
    </body>
    
    </html>
    {% endblock %}

web/templates/web/order2.html
{% extends 'web/base.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

  <!-- Bootstrap CSS -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh">

  <link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'order.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static '1.1 grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '1.3 grid.css' %}">

  <!--GOOGLE Fonts-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap"
    rel="stylesheet">


  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>DioniWines</title>
</head>

<body>
  <header>


    <!-- <a href="{% url 'home' %}">Home</a> -->

  </header>

  <div class="content" style="zoom: 125%; margin-top: 7%;">

    <a href="{% url 'order' %}"><img
        style="margin-top: 3%; border: 2px solid #39e622; text-decoration:none;" src="{% static 'GB.png' %}" width="3%"
        height="3%" alt="Britain Flag">
    </a>

    <a href="{% url 'greekorder' %}"><img
        style="font-weight: 300; margin-left: 2%; margin-top: 3.1%; text-decoration:none;" src="{% static 'GR.png' %}"
        width="3%" height="3%" alt="Greek Flag">
    </a>

    <br>
    <br>
    <div class="hero-text-box" style="
                        display: inline-block; /* Αλλάζουμε το a απο inline Element σε Inline Block για να μπορεί να δεχτεί padding και font-weight*/
                        padding: 10px 30px;
                        
                        font-weight: 300;
                        text-decoration: none;
                        /* border-radius: 200px;*/
                        transition: background-color 0.2s, border 0.2s, color 0.2s;
                        
                        top: 26%; 
                        color: rgb(12, 12, 12);
                        text-decoration: none;
                        text-transform: uppercase;
                        font-size: 90%;
                  
                        background-color: #4172aa;
                        border: 1px solid #346aa8;
                  
                  
                        ">
    <h1 >Place Your Order</h1>
  </div>
    <!-- <form method="POST" enctype="multipart/form-data"> -->

    <form method="POST" enctype="multipart/form-data">
      <!-- Τη μέθοδο την κανουμε POST γιατι θα στείλουμε δεδομένα στον Server με αυτη τη φόρμα -->
      {% csrf_token %}

      <!-- <img src="/media/customer/default.jpg" width="10%" alt="customer photo">--> <br>

      <label>Your Photo</label>
      <small id="usernameHelp" class="form-text text-muted">Upload Your Photo Here.Optional.</small><br>

      <div style="
            
            color: rgb(199, 199, 199); 
            display: inline-block; 
            padding: 10px; 
            background-color: teal">
        

        {{ form.customer_photo }}
      
      </div>



      <br><br>

     

        <label>Your First Name</label>

        
        <style>
          #id_customer_first_name {
              width: 30%;
            }
          #id_customer_second_name {
            width: 30%;
          }
          #id_town {
            width: 30%;
          }
          #id_address {
            width: 30%;
          }
          #id_postalcode {
            width: 30%;
          }
          #id_order_description {
            width: 30%;
          }
          #id_order {
            width: 30%;
          }
          
        </style>
        
        
        <div style="
            
            margin-left: 3.1%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
      
            ">

          {{ form.customer_first_name }}
        </div>


        
        <br> 
        <br>
     


      <label>Your Second Name</label>

      
      <div style="
            
            margin-left: 1.3%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
      
            ">
        {{ form.customer_second_name }}
      </div>

      <br> 
      <br>
      <label for="country">country</label>
      <div
      style="
            margin-left: 8%;
            color: rgb(26, 26, 26); 
            display: inline-block; 
            padding: 10px; 
            background-color: teal">

        {{ form.country }}
      </div>
      
      <br> 
      <br>

      <label>Town</label>
      
      <div style="
                  margin-left: 9.4%;
                  box-sizing: border-box;
                  color: rgb(27, 27, 27);  
                  display: inline; 
                  padding: 10px; 
                  background-color: teal;
            
                  ">
        {{ form.town }}
      </div>

      <br>
      <br>
      <label>Address</label>
      
      <div style="
                        margin-left: 7.6%;
                        box-sizing: border-box;
                        color: rgb(27, 27, 27);  
                        display: inline; 
                        padding: 10px; 
                        background-color: teal;
                  
                        ">
        {{ form.address }}
      </div>
      <br>
      <br>

      <label>postalcode</label>
      
      <div style="
        margin-left: 6%;
        box-sizing: border-box;
        color: rgb(27, 27, 27);  
        display: inline; 
        padding: 10px; 
        background-color: teal;

        ">
        {{ form.postalcode }}
      </div>

      
        <br>
      <br>
      <label>Order Description</label> <br> <br>
      <div 
      
      style="
            margin-left: 3%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
      
            ">

        {{ form.order_description }}
      </div>

      <br>
      <br>
      <label>Order Details</label> <br>

      <div 
      
      style="
            margin-left: 3%;
            color: rgb(27, 27, 27);  
          ">
      
        {{ form.order }}
      </div>

      <br>
      <br>
      
      <button type="submit" class="btn btn-primary">Place Order</button>



      <!-- <button type="submit">Leave Feedback</button> -->

    </form>

  </div>


  {% endblock %}

</body>

</html>

web/templates/web/revieworder.html
{% extends 'web/base.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

  <!-- Bootstrap CSS -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh">

  <link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'vieworder.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static '1.1 grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '1.3 grid.css' %}">

  <!--GOOGLE Fonts-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap"
    rel="stylesheet">


  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>DioniWines</title>
</head>

<body>
  <header>


    <!-- <a href="{% url 'home' %}">Home</a> -->

  </header>

  <div class="content" style="zoom: 125%; margin-top: 7%;">

    <a href="{% url 'reviewdeletedorders' vieworders.id%}"><img
        style="margin-top: 3%; border: 2px solid #39e622; text-decoration:none;" src="{% static 'GB.png' %}" width="3%"
        height="3%" alt="Britain Flag">
    </a>

    <a href="{% url 'greekreviewdeletedorders' vieworders.id%}"><img
        style="font-weight: 300; margin-left: 2%; margin-top: 3.1%; text-decoration:none;" src="{% static 'GR.png' %}" 
        width="3%" height="3%" alt="Greek Flag">
    </a>



    <!-- <form method="POST" enctype="multipart/form-data"> -->
    <br> <br>

    <div class="hero-text-box" style="
            display: inline-block; /* Αλλάζουμε το a απο inline Element σε Inline Block για να μπορεί να δεχτεί padding και font-weight*/
            padding: 10px 30px;
            
            font-weight: 300;
            text-decoration: none;
            /* border-radius: 200px;*/
            transition: background-color 0.2s, border 0.2s, color 0.2s;
            
            top: 26%; 
            color: rgb(12, 12, 12);
            text-decoration: none;
            text-transform: uppercase;
            font-size: 90%;
      
            background-color: #34a853c2;
            border: 1px solid #34a853cc;
      
      
            ">


      Order Placed On {{ vieworders.placed }}

    </div>

    <br>
    <br>



    <style>
      #id_customer_first_name {
        width: 30%;
      }

      #id_customer_second_name {
        width: 30%;
      }

      #id_town {
        width: 30%;
      }

      #id_address {
        width: 30%;
      }

      #id_postalcode {
        width: 30%;
      }

      #id_order_description {
        width: 30%;
      }

      #id_order {
        width: 30%;
      }
    </style>



    {% if vieworders.customer_photo %}
    <!--With Photo-->

    <form method="POST" enctype="multipart/form-data">
      <!-- Τη μέθοδο την κανουμε POST γιατι θα στείλουμε δεδομένα στον Server με αυτη τη φόρμα -->
      {% csrf_token %}

      <div class="form-group">
        <img src="{{ vieworders.customer_photo.url }}" width="10%" alt="customer photo">

        <br> <br>

        <label>Your Photo</label>
        <small id="usernameHelp" class="form-text text-muted">Upload Your Photo Here.Optional.</small><br>

        <div style="
            
            color: rgb(199, 199, 199); 
            display: inline-block; 
            padding: 10px; 
            background-color: teal">


          {{ form.customer_photo }}

        </div>
      </div>



      <br>



      <label>Your First Name</label>


      <div style="
            
            margin-left: 3.1%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
      
            ">

        {{ form.customer_first_name }}
      </div>



      <br>
      <br>



      <label>Your Second Name</label>


      <div style="
            
            margin-left: 1.3%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
      
            ">
        {{ form.customer_second_name }}
      </div>

      <br>
      <br>
      <label for="country">country</label>
      <div style="
            margin-left: 8%;
            color: rgb(26, 26, 26); 
            display: inline-block; 
            padding: 10px; 
            background-color: teal">

        {{ form.country }}
      </div>

      <br>
      <br>

      <label>Town</label>

      <div style="
                  margin-left: 9.4%;
                  box-sizing: border-box;
                  color: rgb(27, 27, 27);  
                  display: inline; 
                  padding: 10px; 
                  background-color: teal;
            
                  ">
        {{ form.town }}
      </div>

      <br>
      <br>
      <label>Address</label>

      <div style="
                        margin-left: 7.6%;
                        box-sizing: border-box;
                        color: rgb(27, 27, 27);  
                        display: inline; 
                        padding: 10px; 
                        background-color: teal;
                  
                        ">
        {{ form.address }}
      </div>
      <br>
      <br>

      <label>postalcode</label>

      <div style="
        margin-left: 6%;
        box-sizing: border-box;
        color: rgb(27, 27, 27);  
        display: inline; 
        padding: 10px; 
        background-color: teal;

        ">
        {{ form.postalcode }}
      </div>


      <br>
      <br>
      <label>Order Description</label> <br> <br>
      <div style="
            margin-left: 3%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
      
            ">

        {{ form.order_description }}
      </div>

      <br>
      <br>
      <label>Order Details</label> <br>

      <div style="
            margin-left: 3%;
            color: rgb(27, 27, 27);  
          ">

        {{ form.order }}
      </div>
      <br>
      <br>

      <div class="form">
        Delete: {{ form.deleted }}
      </div>

      <br>
      <br>

      <button type="submit" class="btn btn-primary">Save Changes</button>



      <!-- <button type="submit">Leave Feedback</button> -->

    </form>
    <br>


    {% else %}

    <form method="POST" enctype="multipart/form-data">
      <!-- Τη μέθοδο την κανουμε POST γιατι θα στείλουμε δεδομένα στον Server με αυτη τη φόρμα -->
      {% csrf_token %}

      <div class="form-group">
        <img src="/media/customer/default.jpg" width="10%" alt="customer photo">

        <br> <br>


        <label>Your Photo</label>
        <small id="usernameHelp" class="form-text text-muted">Upload Your Photo Here.Optional.</small><br>

        <div style="
                
                color: rgb(199, 199, 199); 
                display: inline-block; 
                padding: 10px; 
                background-color: teal">


          {{ form.customer_photo }}

        </div>
      </div>

      <br>





      <label>Your First Name</label>


      <div style="
                
                margin-left: 3.1%;
                box-sizing: border-box;
                color: rgb(27, 27, 27);  
                display: inline; 
                padding: 10px; 
                background-color: teal;
          
                ">

        {{ form.customer_first_name }}
      </div>



      <br>
      <br>



      <label>Your Second Name</label>


      <div style="
                
                margin-left: 1.3%;
                box-sizing: border-box;
                color: rgb(27, 27, 27);  
                display: inline; 
                padding: 10px; 
                background-color: teal;
          
                ">
        {{ form.customer_second_name }}
      </div>

      <br>
      <br>
      <label for="country">country</label>
      <div style="
                margin-left: 8%;
                color: rgb(26, 26, 26); 
                display: inline-block; 
                padding: 10px; 
                background-color: teal">

        {{ form.country }}
      </div>

      <br>
      <br>

      <label>Town</label>

      <div style="
                      margin-left: 9.4%;
                      box-sizing: border-box;
                      color: rgb(27, 27, 27);  
                      display: inline; 
                      padding: 10px; 
                      background-color: teal;
                
                      ">
        {{ form.town }}
      </div>

      <br>
      <br>
      <label>Address</label>

      <div style="
                            margin-left: 7.6%;
                            box-sizing: border-box;
                            color: rgb(27, 27, 27);  
                            display: inline; 
                            padding: 10px; 
                            background-color: teal;
                      
                            ">
        {{ form.address }}
      </div>
      <br>
      <br>

      <label>postalcode</label>

      <div style="
            margin-left: 6%;
            box-sizing: border-box;
            color: rgb(27, 27, 27);  
            display: inline; 
            padding: 10px; 
            background-color: teal;
    
            ">
        {{ form.postalcode }}
      </div>


      <br>
      <br>
      <label>Order Description</label> <br> <br>
      <div style="
                margin-left: 3%;
                box-sizing: border-box;
                color: rgb(27, 27, 27);  
                display: inline; 
                padding: 10px; 
                background-color: teal;
          
                ">

        {{ form.order_description }}
      </div>

      <br>
      <br>
      <label>Order Details</label> <br>

      <div style="
                margin-left: 3%;
                color: rgb(27, 27, 27);  
              ">

        {{ form.order }}
      </div>
      <br>
      <br>


      <div class="form" style="color: blanchedalmond;">
        Delete: {{ form.deleted }}
      </div>

      <br>
      <br>

      <button type="submit" class="btn btn-primary">Save Changes</button>



      <!-- <button type="submit">Leave Feedback</button> -->

    </form>
    <br>



    {% endif %}

    <form method="POST" onsubmit="return confirm('Are You Sure ?')"
      action="{% url 'deletedeletedorder' vieworders.id %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Delete For EVER</button>
    </form>

  </div>



  {% endblock %}

</body>

</html>

web/templates/web/welcomefeedback.html
<a href="{% url 'home' %}">Home</a>

<h1>Your Account Just Created</h1>

<h1 style="color: black;">Leave Feedback</h1>


<form method="POST" enctype="multipart/form-data">
  <!-- Τη μέθοδο την κανουμε POST γιατι θα στείλουμε δεδομένα στον Server με αυτη τη φόρμα -->
  {% csrf_token %}
  {{ form.as_p }}
  
  <button type="submit">Leave Feedback</button>

</form>